/*
 * Copyright 2013 Red Hat Inc. and/or its affiliates and other contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.switchyard.quickstarts.rules.interview

global java.lang.String userName
global java.util.Map globals

rule "Is of valid age"
    when
        $a : Applicant( age > 17 )
    then
        globals.put("Result", Boolean.TRUE);
        System.out.println("**** " + $a.getName() + " is an old enough applicant, " + userName + ". ****");
end

rule "Is not of valid age"
    when
        $a : Applicant( age < 18 )
    then
        globals.put("Result", Boolean.FALSE);
        System.err.println("**** " + $a.getName() + " is too young of an applicant, " + userName + ". ****");
end
