
package org.switchyard.quickstarts.soap.mtom;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImageServiceService", targetNamespace = "urn:switchyard-quickstart:soap-mtom:1.0", wsdlLocation = "http://localhost:8080/soap-mtom/ImageServiceService?wsdl")
public class ImageServiceService
    extends Service
{

    private final static URL IMAGESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.switchyard.quickstarts.soap.mtom.ImageServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.switchyard.quickstarts.soap.mtom.ImageServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/soap-mtom/ImageServiceService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '" + url + "', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IMAGESERVICESERVICE_WSDL_LOCATION = url;
    }

    public ImageServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageServiceService() {
        super(IMAGESERVICESERVICE_WSDL_LOCATION, new QName("urn:switchyard-quickstart:soap-mtom:1.0", "ImageServiceService"));
    }

    /**
     * 
     * @return
     *     returns ImageService
     */
    @WebEndpoint(name = "ImageServicePort")
    public ImageService getImageServicePort() {
        return super.getPort(new QName("urn:switchyard-quickstart:soap-mtom:1.0", "ImageServicePort"), ImageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImageService
     */
    @WebEndpoint(name = "ImageServicePort")
    public ImageService getImageServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:switchyard-quickstart:soap-mtom:1.0", "ImageServicePort"), ImageService.class, features);
    }

}
