
package org.switchyard.quickstarts.soap.mtom;

import java.awt.Image;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ImageService", targetNamespace = "urn:switchyard-quickstart:soap-mtom:1.0")
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ImageService {


    /**
     * 
     * @param resizeImage
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "imageResponse", partName = "jpeg")
    public byte[] resizeImage(
        @WebParam(mode = WebParam.Mode.IN, name = "image", partName = "jpeg")
        Holder<byte[]> image);

}
