package org.switchyard.quickstarts.remoteinvoker
global java.util.Map globals

rule "ApproveCredit"
    when
        app : Application(creditScore >= 600)
    then
        System.out.println("Approving credit for " + app.getName());
        app.setApproved(true);
        globals.put("Result", app);
end

rule "DenyCredit"
    when
        app : Application(creditScore < 600)
    then
        System.out.println("Denying credit for " + app.getName());
        app.setApproved(false);
        globals.put("Result", app);
end
