package org.switchyard.quickstarts.demo.cluster
import org.switchyard.Message
global Message message

rule "ApproveCredit"
    when
        app : Application(creditScore >= 600)
    then
        System.out.println("Credit Service : Approving credit for " + app.getName());
        app.setApproved(true);
end

rule "DenyCredit"
    when
        app : Application(creditScore < 600)
    then
        System.out.println("Credit Service : Denying credit for " + app.getName());
        app.setApproved(false);
end
